/** Domain types. Mirrors supabase/migrations/00000000000001_schema.sql. */

export type TaskStatus =
  'backlog' | 'todo' | 'doing' | 'review' | 'blocked' | 'done'
export type Priority = 'high' | 'normal' | 'low'
export type ProjectStatus = 'active' | 'on_hold' | 'done' | 'archived'
export type Health = 'on_track' | 'watch' | 'at_risk'
export type Recurrence =
  | 'daily' | 'weekly' | 'biweekly' | 'monthly' | 'quarterly' | 'custom'

export type Department =
  'brand' | 'marketing' | 'operations' | 'delivery' | 'admin'

export type Platform =
  'linkedin' | 'x' | 'instagram' | 'youtube' | 'facebook' | 'tiktok' | 'newsletter'

export type ContentStatus =
  | 'idea' | 'in_progress' | 'review' | 'ready' | 'published' | 'blocked'

export type ContentKind =
  'post' | 'short' | 'long' | 'carousel' | 'newsletter' | 'article'


export type UserRole = 'owner' | 'admin' | 'manager' | 'member' | 'viewer'
export type UserState = 'invited' | 'active' | 'suspended' | 'deactivated'

export interface Person {
  id: string
  email: string
  name: string
  title: string | null
  job_title: string | null
  avatar_url: string | null
  is_admin: boolean
  is_active: boolean
  role: UserRole
  state: UserState
  timezone: string
  department: Department | null
  function_id: string | null
  slack_user_id: string | null
  invited_at: string | null
  last_seen_at: string | null
}

export interface OrgFunction {
  id: string
  key: string
  name: string
  description: string | null
  color: string
  lead_id: string | null
  slack_channel: string | null
  sort_order: number
  is_active: boolean
}

export interface Client {
  id: string
  name: string
  notes: string | null
  external_url: string | null
  is_active: boolean
}

export interface Project {
  function_id?: string | null
  deleted_at?: string | null
  id: string
  name: string
  description: string | null
  status: ProjectStatus
  health: Health
  owner_id: string
  client_id: string | null
  department: Department
  due_date: string | null
  task_count: number
  done_count: number
  created_at: string
  updated_at: string
  archived_at: string | null
}

export interface Task {
  /** Set when a task was generated by something else, a review, an import. */
  source_kind?: string | null
  source_id?: string | null
  id: string
  project_id: string | null
  title: string
  notes: string | null
  status: TaskStatus
  priority: Priority
  assignee_id: string | null
  due_date: string | null
  department: Department
  function_id: string
  blocked_reason: string | null
  started_at: string | null
  review_requested_at: string | null
  estimate_hours: number | null
  position: number
  recurring_id: string | null
  /** The procedure this task follows, if it has one. */
  sop_id: string | null
  done_at: string | null
  created_by: string | null
  created_at: string
  updated_at: string
}

export interface ChecklistItem {
  id: string
  task_id: string
  content: string
  is_done: boolean
  position: number
}

export interface Comment {
  id: string
  task_id: string
  author_id: string
  body: string
  created_at: string
}

/** One line of a schedule. A task owns as many as it needs. */
export interface RecurrenceRule {
  id: string
  kind: 'weekday' | 'day_of_month' | 'last_day' | 'nth_weekday'
  /** 0=Sunday..6=Saturday. */
  day_of_week: number | null
  day_of_month: number | null
  /** 1-4 counts from the start of the month; -1 means the last such weekday. */
  week_of_month: number | null
}

export interface RecurringTask {
  id: string
  title: string
  notes: string | null
  project_id: string | null
  assignee_id: string | null
  priority: Priority
  frequency: Recurrence
  /** "Every 3 weeks" / "every 2 months". 1 for the plain frequencies. */
  interval_n: number
  starts_on: string
  ends_on: string | null
  ends_after: number | null
  occurrences_made: number
  sop_id: string | null
  checklist: string[]
  next_due: string
  is_active: boolean
  /** Legacy single-schedule columns. Superseded by `rules`; read by nothing. */
  day_of_week: number | null
  day_of_month: number | null
  week_of_month: number | null
  /** The schedule, joined by getRecurring. */
  rules?: RecurrenceRule[]
  assignee?: Pick<Person, 'id' | 'name' | 'avatar_url'> | null
  project?: Pick<Project, 'id' | 'name'> | null
}

/** One line of the daily rally, shown above Command Center. */
export interface RallyLine {
  body: string
  source: string | null
}

/** A procedure, stored in Drive and pointed at from here. */
export interface Sop {
  id: string
  title: string
  url: string
  summary: string | null
  function_id: string | null
  is_essential: boolean
  sort_order: number
  is_active: boolean
}

export interface Search {
  project_id: string
  role_title: string
  opened_on: string
  target_count: number
  target_days: number
  submitted: number
  interviews: number
  placements: number
  updated_at: string | null
}

// --- What the UI actually renders -------------------------------------------

export interface TaskRow extends Task {
  project?: Pick<Project, 'id' | 'name' | 'department'> | null
  assignee?: Pick<Person, 'id' | 'name' | 'avatar_url'> | null
  creator?: Pick<Person, 'id' | 'name' | 'avatar_url'> | null
  fn?: Pick<OrgFunction, 'id' | 'key' | 'name' | 'color'> | null
  /** The procedure to follow, shown on the task itself. */
  sop?: Pick<Sop, 'id' | 'title' | 'url'> | null
  collaborators?: Pick<Person, 'id' | 'name' | 'avatar_url'>[]
  checklist_total?: number
  checklist_done?: number
  comment_count?: number
}

export interface ProjectRow extends Project {
  owner?: Pick<Person, 'id' | 'name' | 'avatar_url'> | null
  client?: Pick<Client, 'id' | 'name'> | null
  search?: Search | null
  overdue_count?: number
}

export interface Content {
  id: string
  title: string
  kind: ContentKind
  platform: Platform
  status: ContentStatus
  hook: string | null
  body: string | null
  script: string | null
  notes: string | null
  owner_id: string | null
  publish_date: string | null
  published_url: string | null
  source: string
  source_ref: string | null
  generated_at: string | null
  position: number
  created_at: string
  updated_at: string
}

export interface ContentRow extends Content {
  owner?: Pick<Person, 'id' | 'name' | 'avatar_url'> | null
}

export interface VoiceProfile {
  id: number
  person_id: string | null
  tone: string | null
  beliefs: string | null
  avoid: string | null
  samples: string | null
  audience: string | null
}


export interface SlackSettings {
  id: number
  webhook_url: string | null
  default_channel: string | null
  notify_assigned: boolean
  notify_completed: boolean
  notify_waiting: boolean
  notify_overdue: boolean
  notify_comment: boolean
  daily_digest: boolean
  is_connected: boolean
  last_sent_at: string | null
  last_error: string | null
}

export interface Calendar {
  id: string
  person_id: string | null
  email: string
  label: string
  provider: string
  color: string
  is_active: boolean
  last_synced_at: string | null
  last_error: string | null
}

export interface CalendarEvent {
  id: string
  calendar_id: string
  external_id: string
  subject: string
  starts_at: string
  ends_at: string | null
  time_zone: string | null
  is_all_day: boolean
  location: string | null
  organizer: string | null
  attendees: string[]
  show_as: string | null
  is_cancelled: boolean
  web_link: string | null
  categories: string[]
}

export interface DriveFile {
  id: string
  external_id: string
  title: string
  mime_type: string | null
  folder: string | null
  view_url: string
  icon_kind: string | null
  size_bytes: number | null
  modified_at: string | null
  project_id: string | null
  content_id: string | null
}

export interface Integration {
  key: string
  label: string
  is_connected: boolean
  last_synced_at: string | null
  last_error: string | null
}

export interface PriorityTarget {
  priority: Priority
  label: string
  /** Turnaround promise, in hours. */
  hours: number
  description: string
}

// --- Activity & notifications -------------------------------------------------

export interface ActivityEntry {
  id: string
  entity_type: string
  entity_id: string
  actor_id: string | null
  verb: string
  field: string | null
  from_value: string | null
  to_value: string | null
  summary: string | null
  created_at: string
  actor?: Pick<Person, 'id' | 'name' | 'avatar_url'> | null
}

export type NotifyKind =
  | 'task_assigned' | 'task_started' | 'task_review_requested' | 'task_blocked'
  | 'task_completed' | 'task_due_soon' | 'task_overdue' | 'comment_mention'
  | 'comment_reply' | 'content_review' | 'content_published' | 'gtm_review'
  | 'recurring_created'

export interface Notification {
  id: string
  person_id: string
  kind: NotifyKind
  title: string
  body: string | null
  url: string | null
  entity_type: string | null
  entity_id: string | null
  actor_id: string | null
  read_at: string | null
  created_at: string
}

export interface NotificationPreference {
  person_id: string
  kind: NotifyKind
  in_app: boolean
  slack: boolean
}

export interface Attachment {
  id: string
  entity_type: string
  entity_id: string
  file_name: string
  storage_path: string | null
  external_url: string | null
  mime_type: string | null
  size_bytes: number | null
  uploaded_by: string | null
  created_at: string
}

// --- Content ---------------------------------------------------------------------

export interface ContentPillar {
  id: string
  name: string
  description: string | null
  color: string
  sort_order: number
  is_active: boolean
}

export interface ContentPlatformRow {
  content_id: string
  platform: Platform
  caption: string | null
  scheduled_at: string | null
  published_at: string | null
  published_url: string | null
  external_post_id: string | null
}

export interface ContentLink {
  id: string
  content_id: string
  url: string
  label: string | null
  kind: string
  sort_order: number
}

export interface ContentAsset {
  id: string
  content_id: string
  kind: string
  file_name: string
  storage_path: string | null
  external_url: string | null
  mime_type: string | null
  size_bytes: number | null
}

export interface ContentMetric {
  id: string
  content_id: string
  platform: Platform
  metric: string
  value: number
  observed_at: string
  source: string
}

// --- GTM ---------------------------------------------------------------------------

export type GtmStage =
  | 'target' | 'researching' | 'contacts_found' | 'pending_review'
  | 'approved_build' | 'pending_outreach' | 'outreach_active'
  | 'engaged' | 'complete' | 'hold'

export type GtmOutcome =
  | 'meeting' | 'nurture' | 'not_interested' | 'no_response' | 'not_a_fit'

export type ContactStatus =
  | 'planned' | 'drafting' | 'ready' | 'contacted'
  | 'responded' | 'no_response' | 'not_interested'

export type DraftStatus =
  | 'draft' | 'ready_for_review' | 'approved' | 'needs_revision' | 'ready_for_outbound'

export interface GtmAccount {
  id: string
  company: string
  website: string | null
  industry: string | null
  owner_id: string | null
  researcher_id: string | null
  stage: GtmStage
  priority: Priority
  signal_source: string | null
  signal_note: string | null
  notes: string | null
  assigned_on: string
  completed_at: string | null
  external_url: string | null
  created_at: string
}

export interface GtmAccountRow extends GtmAccount {
  owner?: Pick<Person, 'id' | 'name' | 'avatar_url'> | null
  researcher?: Pick<Person, 'id' | 'name' | 'avatar_url'> | null
  contact_count?: number
  draft_count?: number
  outcome?: GtmOutcome | null
  outcome_note?: string | null
  next_action?: string | null
  next_action_on?: string | null
  nurture_until?: string | null
  current_contact_id?: string | null
  current_contact?: { id: string; name: string; title: string | null } | null
  why_now?: string | null
  sw_status?: string
  approved_by?: string | null
  /** Who confirmed the SourceWhale load, and when. */
  sw_loaded_by?: string | null
  sw_loaded_at?: string | null
  sw_load_note?: string | null
  approved_at?: string | null
  launched_by?: string | null
  launched_at?: string | null
  next_eligible_on?: string | null
  hold_reason?: string | null
  hold_until?: string | null
  attempt_count?: number
}

export interface GtmContact {
  id: string
  account_id: string
  name: string
  title: string | null
  linkedin_url: string | null
  email: string | null
  phone: string | null
  seniority: number
  /** For a hiring manager: the function they hire for. */
  hiring_for?: string | null
  rationale: string | null
  notes: string | null
  persona_order?: number
  sw_status?: string
  why_this_person?: string | null
  contacted_at?: string | null
  responded_at?: string | null
  eligible_on?: string | null
  copy_body?: string | null
  copy_status?: string
  copy_note?: string | null
}

export interface OutreachDraft {
  /** The three drafted options, loaded with the draft. */
  variations?: { id: string; slot: number; subject: string | null; body: string | null }[]
  research_url?: string | null
  final_subject?: string | null
  final_body?: string | null
  id: string
  account_id: string
  contact_id: string | null
  subject: string | null
  body: string | null
  personalization: string | null
  signal: string | null
  status: DraftStatus
  reviewed_by: string | null
  reviewed_at: string | null
  review_note: string | null
  created_at: string
}

export interface SlackChannel {
  id: string
  function_id: string | null
  project_id: string | null
  channel_id: string
  channel_name: string
}

export interface Invitation {
  id: string
  email: string
  name: string
  role: UserRole
  function_id: string | null
  job_title: string | null
  invited_by: string | null
  invited_at: string
  expires_at: string
  accepted_at: string | null
}


/** One publication: a piece of content that went out on one platform. */
/**
 * What a published post did.
 *
 * Every field is nullable: no platform reports all of them, and a rate whose
 * denominator is missing is null rather than zero, "not reported" and
 * "reported as zero" are different facts, and only one of them should drag an
 * average down.
 */
export interface ContentPerformance {
  content_id: string
  platform: Platform
  impressions: number | null
  reach: number | null
  video_views: number | null
  reactions: number | null
  comments: number | null
  shares: number | null
  saves: number | null
  clicks: number | null
  link_clicks: number | null
  new_followers: number | null
  new_connections: number | null
  inbound_dms: number | null
  leads: number | null
  meetings: number | null
  engagements: number | null
  engagement_rate: number | null
  ctr: number | null
  link_ctr: number | null
  connection_rate: number | null
  lead_rate: number | null
  meeting_rate: number | null
  updated_at: string | null
}

export interface PublicationRow {
  metrics?: ContentPerformance | null
  platform: Platform
  published_at: string
  published_url: string | null
  content: {
    id: string
    title: string
    kind: ContentKind
    pillar: string | null
    created_at: string
    owner: { id: string; name: string; avatar_url: string | null } | null
  }
}


/** One finished item in the Archive (§8). Tasks and content, unified. */
export interface ArchiveItem {
  kind: 'task' | 'content'
  id: string
  title: string
  archived_at: string
  archived_by: string | null
  final_status: string
  function_id: string | null
  project_id: string | null
  owner_id: string | null
  created_at: string
  reopen_count: number
}


/** A requisition (spec §12-24). Scores are derived; never write them by hand. */
export interface RequisitionRow {
  /** Intake fields the edit drawer exposes; all present on the table. */
  date_received?: string
  hm_access?: string | null
  notes?: string | null
  comp_min?: number | null
  comp_max?: number | null
  consequence?: string | null
  intake_with?: string | null
  process_defined?: string | null
  work_arrangement?: string | null
  relocation?: string | null
  clearance?: string | null
  industry_need?: string | null
  must_haves?: string | null
  adjacent_ok?: string | null
  /** The sourcing sprint, computed by requisition_board. */
  search_difficulty?: 'easy' | 'medium' | 'hard'
  sprint_target?: number
  sprint_target_override?: number | null
  active_candidates?: number
  candidates_needed?: number
  next_action?: string | null
  sourcing_state?: string
  age_days?: number
  id: string
  company: string
  role_title: string
  openings: number
  comp_target: number | null
  fee_percent: number | null
  agreement_signed: boolean
  search_type: string | null
  competition: string | null
  approval: string | null
  target_start: string | null
  initial_grade: string | null
  live_grade: string | null
  initial_close_pct: number | null
  live_close_pct: number | null
  recommended_action: string | null
  delivery_need: string | null
  guardrail_note: string | null
  viable_candidates: number
  best_stage: string
  status: string
  owner_id: string | null
  owner?: { id: string; name: string; avatar_url: string | null } | null
  created_at: string
}


/** A factual claim behind outreach copy, with its source (§60). */
export interface GtmEvidence {
  id: string
  account_id: string
  claim: string
  source_title: string | null
  source_url: string | null
  published_on: string | null
  verified_at: string | null
  verified_by: string | null
  notes: string | null
}


/** One account's next action, derived from what has already happened. */
export interface ActionItem {
  account_id: string
  company: string
  priority: 'high' | 'normal' | 'low'
  stage: string
  action_type: string
  owner_id: string | null
  due_on: string
  urgency: 'overdue' | 'today' | 'upcoming' | 'waiting'
  reason: string
  sort_key: number
  persona_count: number
  contacted_count: number
  last_activity: string
  next_persona_name: string | null
  next_persona_title: string | null
  current_persona_name: string | null
  current_persona_title: string | null
  current_contacted_at: string | null
  next_copy_status: string | null
}
